### ISSUE TITLE
Navbar menu become misaligned after menu turn into mobile then back to mobile

### ISSUE THREAD

**Issue by dehamzah** [helpscout/seed-navbar#4]
As title said, this can happen if i open the menu mobile then close it back. It seems this misaligned caused by js that make the element height into 0.

```
<div class="c-navbar__item navbar-collapse collapse" id="navbar" style="height: 0px;">
```

See this gif to reproduce the bug.
![bug_navbar](https://user-images.githubusercontent.com/6959476/34516112-6c5a32ea-f0b0-11e7-8794-d005516b9ba6.gif)

**Comment by dehamzah** [comment]
I am seeing how this implemented in bootstrap, and this can be fixed by this.

```
@media (min-width: 768px) {
  .c-navbar__item.collapse {
    height: auto !important;
  }
}
```

but i don't understand the code in the source code 😅
for pull request

**Comment by ItsJonQ** [comment]
Oo! Thank you so much! I'll take a look at this later today 💪
